name: flashbar_flutter
description: A highly customizable, versatile and easy-to-use flashbar for Flutter, providing snackbars, notifications, alerts, and toasts for app bars and bottom bars.
version: 1.0.1
homepage: https://github.com/laraholand/flashbar_flutter
repository: https://github.com/laraholand/flashbar_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

# ----------------------------
# Keywords for Pub.dev search
# ----------------------------
keywords:
  - flashbar
  - snackbar
  - toast
  - notification
  - flutter
  - ui
  - alert
  - appbar_notification
  - appbar_toast
  - bottom_notification
  - bottom_toast